### PR TITLE
Add download scripts to ooipy

### PR DESCRIPTION
**Pull request by John-Ragland**
I'm going to go ahead and create this PR and we can update it as we add more functionality

### CODE REVIEW

**Comment by John-Ragland** [comment]
Hey @anishdixit-uw, would you mind testing out this script and see if it works for you?

**Comment by John-Ragland** [comment]
I think the unit tests are failing because we need to add xarray as a dependancy

**Comment by anishdixit-uw** [comment]
Okay @John-Ragland , I'll try running the script locally

**Review by anishdixit-uw — COMMENTED** [review]
Just had to install the tqdm library but the download works properly following the instructions to run download_hydrophone_data.py.

**Comment by John-Ragland** [comment]
> Just had to install the tqdm library but the download works properly following the instructions to run download_hydrophone_data.py.

Okay, I can add tqdm to the required packages. And after figuring out why pre-commit is failing, this will be ready to merge.

**Comment by anishdixit-uw** [comment]
@John-Ragland  I figured the issue with pre-commit, it fails for flake8, which is just a styling check.

If you replace line 124: 
`filename = f'{args.output_path}/{hdata_ds.stats.location}_{hdata_ds.stats.starttime.strftime("%Y%m%dT%H%M%S")}_{hdata_ds.stats.endtime.strftime("%Y%m%dT%H%M%S")}'`

With this block of code:

```
  op_path = args.output_path
  hdat_loc = hdata_ds.stats.location
  hdat_start_time = hdata_ds.stats.starttime.strftime("%Y%m%dT%H%M%S")
  hdat_end_time = hdata_ds.stats.endtime.strftime("%Y%m%dT%H%M%S")
  filename = f'{op_path}/{hdat_loc}_{hdat_start_time}_{hdat_end_time}'
```

It should now pass

**Comment by John-Ragland** [comment]
Added your code block. I had thought that the pre-commit stuff fixed the styling automatically. For now I can just fix this line manually like you suggested.

**Review by anishdixit-uw — APPROVED** [review]
All checks passed

**Comment by John-Ragland** [comment]
🎉

**Pull request merged**
